### ISSUE TITLE
Make first meeting ideas as document so we don't forget

### ISSUE THREAD

**Issue by LimePencil** [WesleyCodingTeam/textbaseRPG#12]
Turn what we discussed into document for later.

**Comment by LimePencil** [comment]
Write it in the settingFile.java

**Comment by junboi** [comment]
Character, is the youngest in their poor family, he just grew to an age where he/she can start working, they wake up with the help of their older sister and heads off to the guild where they start working as a gatherer. During their time gathering, they get attacked by a great wolf, a C rank monster, just before their death, a they see a vision of the hero that was told in fables. The vision gives him the blessing of the Elevator. The Character, empowered by the dead hero, manages to kill the wolf (Tutorial) They then return to the guild and shows what they've gathered. They get immediately promoted to D rank. At first his only motivation was the money, but as he ranks up, he slowly wants to become a hero. He slowly learns of where the monsters come from, so that he can finally protect everyone. When he finally reaches S rank, he finds out the truth of another world from a forbidden library at the end of the dungeon. This other world is trying to destroy this world so that their world could be saved, our hero has multiple battles with the other worlders while fighting their monsters. When he finally gets the upper hand on the other world's hero, they decide not to kill her. This angers the demon that controls the two worlds, and the heros fight together to kill the Demon.
